version: "3.9"
services:
  subgen-ui:
    build: .
    container_name: subgen-ui
    ports:
      - "8585:8585"
    volumes:
      - ./content:/app/content:ro
      - ./config:/app/config:rw
    environment:
      - NODE_ENV=production
    restart: unless-stopped
